export const scopeAmenitiesData = {
  PROPERTY: {
    COLLABORATION: [
      {
        id: '64a17439c4a5473c4ffe3194',
        Name: 'Community Events and Workshops',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3195',
        Name: 'Networking Opportunities',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3196',
        Name: 'Co-working Spaces',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3197',
        Name: 'Shared Lounges',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3198',
        Name: 'Collaboration Tools (e.g., Whiteboards, Projectors)',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'PROPERTY',
      },
    ],
    CONNECTIVITY: [
      {
        id: '64a17439c4a5473c4ffe318b',
        Name: 'Ethernet Ports',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe318a',
        Name: 'Wi-Fi Connectivity',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe318c',
        Name: 'Power Outlets',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe318d',
        Name: 'Charging Stations',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe318e',
        Name: 'Printing and Scanning Facilities',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'PROPERTY',
      },
    ],
    REFRESHMENTS: [
      {
        id: '64a17439c4a5473c4ffe318f',
        Name: 'Coffee and Tea Stations',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3190',
        Name: 'Snack Vending Machines',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3191',
        Name: 'Water Dispensers',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3192',
        Name: 'Kitchenette or Pantry',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3193',
        Name: 'Microwaves and Refrigerators',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'PROPERTY',
      },
    ],
    SAFETY: [
      {
        id: '64a17439c4a5473c4ffe317e',
        Name: 'Fire Safety Equipment',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe317b',
        Name: 'CCTV Surveillance',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe317f',
        Name: 'Emergency Exits',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'PROPERTY',
      },
    ],
    SPACE: [
      {
        id: '64a17439c4a5473c4ffe3181',
        Name: 'Comfortable Seating',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3182',
        Name: 'Air Conditioning',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3183',
        Name: 'Natural Lighting',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3184',
        Name: 'Noise-Cancelling Features',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3180',
        Name: 'High-Speed Internet',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'PROPERTY',
      },
    ],
    SUPPORT: [
      {
        id: '64a17439c4a5473c4ffe3199',
        Name: 'Reception Services',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe319b',
        Name: 'IT Support',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe319c',
        Name: 'Administrative Assistance',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe319d',
        Name: 'On-site Staff',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe319a',
        Name: 'Mail Handling',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'PROPERTY',
      },
    ],
    WORKSPACE: [
      {
        id: '64a17439c4a5473c4ffe3187',
        Name: 'Meeting Rooms',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3185',
        Name: 'Dedicated Desks',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3186',
        Name: 'Private Cabins',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3188',
        Name: 'Conference Facilities',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'PROPERTY',
      },
      {
        id: '64a17439c4a5473c4ffe3189',
        Name: 'Phone Booths',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'PROPERTY',
      },
    ],
  },

  OFFERING: {
    COLLABORATION: [
      {
        id: '64a17439c4a5473c4ffe3194',
        Name: 'Community Events and Workshops',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3195',
        Name: 'Networking Opportunities',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3196',
        Name: 'Co-working Spaces',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3197',
        Name: 'Shared Lounges',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3198',
        Name: 'Collaboration Tools (e.g., Whiteboards, Projectors)',
        Image: '',
        info: '',
        category: 'COLLABORATION',
        scope: 'OFFERING',
      },
    ],
    CONNECTIVITY: [
      {
        id: '64a17439c4a5473c4ffe318b',
        Name: 'Ethernet Ports',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe318a',
        Name: 'Wi-Fi Connectivity',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe318c',
        Name: 'Power Outlets',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe318d',
        Name: 'Charging Stations',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe318e',
        Name: 'Printing and Scanning Facilities',
        Image: '',
        info: '',
        category: 'CONNECTIVITY',
        scope: 'OFFERING',
      },
    ],
    REFRESHMENTS: [
      {
        id: '64a17439c4a5473c4ffe318f',
        Name: 'Coffee and Tea Stations',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3190',
        Name: 'Snack Vending Machines',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3191',
        Name: 'Water Dispensers',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3192',
        Name: 'Kitchenette or Pantry',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3193',
        Name: 'Microwaves and Refrigerators',
        Image: '',
        info: '',
        category: 'REFRESHMENTS',
        scope: 'OFFERING',
      },
    ],
    SAFETY: [
      {
        id: '64a17439c4a5473c4ffe317e',
        Name: 'Fire Safety Equipment',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe317b',
        Name: 'CCTV Surveillance',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe317f',
        Name: 'Emergency Exits',
        Image: '',
        info: '',
        category: 'SAFETY',
        scope: 'OFFERING',
      },
    ],
    SPACE: [
      {
        id: '64a17439c4a5473c4ffe3181',
        Name: 'Comfortable Seating',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3182',
        Name: 'Air Conditioning',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3183',
        Name: 'Natural Lighting',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3184',
        Name: 'Noise-Cancelling Features',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3180',
        Name: 'High-Speed Internet',
        Image: '',
        info: '',
        category: 'SPACE',
        scope: 'OFFERING',
      },
    ],
    SUPPORT: [
      {
        id: '64a17439c4a5473c4ffe3199',
        Name: 'Reception Services',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe319b',
        Name: 'IT Support',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe319c',
        Name: 'Administrative Assistance',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe319d',
        Name: 'On-site Staff',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe319a',
        Name: 'Mail Handling',
        Image: '',
        info: '',
        category: 'SUPPORT',
        scope: 'OFFERING',
      },
    ],
    WORKSPACE: [
      {
        id: '64a17439c4a5473c4ffe3187',
        Name: 'Meeting Rooms',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3185',
        Name: 'Dedicated Desks',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3186',
        Name: 'Private Cabins',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3188',
        Name: 'Conference Facilities',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'OFFERING',
      },
      {
        id: '64a17439c4a5473c4ffe3189',
        Name: 'Phone Booths',
        Image: '',
        info: '',
        category: 'WORKSPACE',
        scope: 'OFFERING',
      },
    ],
  },
}
